-- MySQL Script generated by MySQL Workbench
-- mer. 07 avril 2021 09:55:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exo204
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exo204
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exo204` ;
USE `exo204` ;

-- -----------------------------------------------------
-- Table `exo204`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo204`.`profile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `account_number` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `children_number` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `profile_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `exo204`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo204`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo204`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo204`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo204`.`profile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `account_number` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `children_number` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `profile_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `exo204`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo204`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo204`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo204`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo204`.`user_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_fk` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_role_user_fk_idx` (`user_fk` ASC) VISIBLE,
  INDEX `fk_user_role_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `user_role_user_fk`
    FOREIGN KEY (`user_fk`)
    REFERENCES `exo204`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `exo204`.`role` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
